# CRE Workflow Settings for world-id-verifier

local-simulation:
  user-workflow:
    workflow-name: "world-id-verifier"
  workflow-artifacts:
    workflow-path: "./index.ts"
    config-path: "./config.json"
